// config/roles.js

export const ROLES = {
    ADMIN: 'ADMIN',
    VENDEDOR: 'VENDEDOR',
    AUDITOR: 'AUDITOR',
    ASISTENTE: 'ASISTENTE' 
}

export const PERMISOS = {

    // 👥 MÓDULO DE CLIENTES
    LEER_CLIENTES: [ROLES.ADMIN, ROLES.VENDEDOR, ROLES.AUDITOR, ROLES.ASISTENTE],
    ESCRIBIR_CLIENTES: [ROLES.ADMIN, ROLES.VENDEDOR],
    ELIMINAR_CLIENTES: [ROLES.ADMIN],

    // ⚙️ MÓDULO DE USUARIOS
    LEER_USUARIOS: [ROLES.ADMIN],
    ESCRIBIR_USUARIOS: [ROLES.ADMIN],
    ELIMINAR_USUARIOS: [ROLES.ADMIN],

    // 📦 MÓDULO DE PRODUCTOS (INVENTARIO)
    LEER_PRODUCTOS: [ROLES.ADMIN, ROLES.VENDEDOR, ROLES.AUDITOR, ROLES.ASISTENTE],
    ESCRIBIR_PRODUCTOS: [ROLES.ADMIN, ROLES.VENDEDOR], // Solo admin mete o saca stock manualmente
    ELIMINAR_PRODUCTOS: [ROLES.ADMIN],

    // 📂 MÓDULO DE CATEGORÍAS
    LEER_CATEGORIAS: [ROLES.ADMIN, ROLES.VENDEDOR, ROLES.AUDITOR, ROLES.ASISTENTE],
    ESCRIBIR_CATEGORIAS: [ROLES.ADMIN, ROLES.VENDEDOR, ROLES.AUDITOR],
    ELIMINAR_CATEGORIAS: [ROLES.ADMIN],

    // 🚚 MÓDULO DE PROVEEDORES
    LEER_PROVEEDORES: [ROLES.ADMIN, ROLES.AUDITOR], // Un vendedor no suele necesitar ver a quién le compras
    ESCRIBIR_PROVEEDORES: [ROLES.ADMIN],
    ELIMINAR_PROVEEDORES: [ROLES.ADMIN],

    // 💰 MÓDULO DE VENTAS
    LEER_VENTAS: [ROLES.ADMIN, ROLES.VENDEDOR, ROLES.AUDITOR], 
    ESCRIBIR_VENTAS: [ROLES.ADMIN, ROLES.VENDEDOR], // Ambos pueden facturar
    MODIFICAR_VENTAS: [ROLES.ADMIN], // Solo admin anula o modifica facturas pasadas
    ELIMINAR_VENTAS: [ROLES.ADMIN],

    // 💳 MÓDULO DE CRÉDITOS (FIADOS)
    LEER_CREDITOS: [ROLES.ADMIN, ROLES.VENDEDOR, ROLES.AUDITOR],
    ESCRIBIR_CREDITOS: [ROLES.ADMIN, ROLES.VENDEDOR], // Vendedor puede fiar
    ELIMINAR_CREDITOS: [ROLES.ADMIN],
}