export const ROLES = {
    ADMIN: 'ADMIN',
    VENDEDOR: 'VENDEDOR',
    AUDITOR: 'AUDITOR',
    ASISTENTE: 'ASISTENTE'
}

export const PERMISOS = {

    //MÓDULO DE CLIENTES
    LEER_CLIENTES: [ROLES.ADMIN, ROLES.VENDEDOR, ROLES.AUDITOR, ROLES.ASISTENTE],
    ESCRIBIR_CLIENTES: [ROLES.ADMIN, ROLES.VENDEDOR],
    ELIMINAR_CLIENTES: [ROLES.ADMIN],

    //MÓDULO DE USUARIOS
    LEER_USUARIOS: [ROLES.ADMIN],
    ESCRIBIR_USUARIOS: [ROLES.ADMIN],
    ELIMINAR_USUARIOS: [ROLES.ADMIN],

    
}